export const READ_BOOKS_SUCCESFUL = 'READ_BOOKS_SUCCESFUL';
export const READ_BOOKS_PENDING = 'READ_BOOKS_PENDING';
export const READ_BOOKS_FAILURE = 'READ_BOOKS_FAILURE';

export const CONTACTS_SUCCESFUL = 'CONTACTS_SUCCESFUL';
export const CONTACTS_PENDING = 'CONTACTS_PENDING';
export const CONTACTS_FAILURE = 'CONTACTS_FAILURE';

export const APPOINTMENTS_SUCCESFUL = 'APPOINTMENTS_SUCCESFUL';
export const APPOINTMENTS_PENDING = 'APPOINTMENTS_PENDING';
export const APPOINTMENTS_FAILURE = 'APPOINTMENTS_FAILURE';

export const FEES_SUCCESFUL = 'FEES_SUCCESFUL';
export const FEES_PENDING = 'FEES_PENDING';
export const FEES_FAILURE = 'FEES_FAILURE';

export const POST_APPOINTMENTS_SUCCESFUL = 'POST_APPOINTMENTS_SUCCESFUL';
export const POST_APPOINTMENTS_FAILURE = 'POST_APPOINTMENTS_FAILURE';

export const INFO_CITATIONS_SUCCESSFUL = 'INFO_CITATIONS_SUCCESSFUL';
export const INFO_LICENSE_SUCCESSFUL = 'INFO_LICENSE_SUCCESSFUL';
export const INFO_REQUEST_PENDING = 'INFO_REQUEST_PENDING';
export const INFO_REQUEST_FAILURE = 'INFO_REQUEST_FAILURE';
export const SWITCH_INFORMATION_VIEW = 'SWITCH_INFORMATION_VIEW';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_FAILED = "UPDATE_CONTACT_FAILED";
export const UPDATE_CONTACT_SUCCESS ="UPDATE_CONTACT_SUCCESS";

export const FINDING_PAYMENT = "FINDING_PAYMENT";
export const PAYMENT_FOUND = "PAYMENT_FOUND";
export const PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND";

export const VEHICLEDETAILS_SUCCESSFUL = 'VEHICLEDETAILS_SUCCESSFUL';
export const VEHICLEDETAILS_PENDING = 'VEHICLEDETAILS_PENDING';
export const VEHICLEDETAILS_FAILURE = 'VEHICLEDETAILS_FAILURE';