export const READ_BOOKS_SUCCESFUL = 'READ_BOOKS_SUCCESFUL';
export const READ_BOOKS_PENDING = 'READ_BOOKS_PENDING';
export const READ_BOOKS_FAILURE = 'READ_BOOKS_FAILURE';
export const CONTACTS_SUCCESFUL = 'CONTACTS_SUCCESFUL';
export const CONTACTS_PENDING = 'CONTACTS_PENDING';
export const CONTACTS_FAILURE = 'CONTACTS_FAILURE';
export const INFO_CITATIONS_SUCCESSFUL = 'INFO_CITATIONS_SUCCESSFUL';
export const INFO_LICENSE_SUCCESSFUL = 'INFO_LICENSE_SUCCESSFUL';
export const INFO_REQUEST_PENDING = 'INFO_REQUEST_PENDING';
export const INFO_REQUEST_FAILURE = 'INFO_REQUEST_FAILURE';
export const SWITCH_INFORMATION_VIEW = 'SWITCH_INFORMATION_VIEW';

